login: &login
  adapter: mysql
  database: reference_development
  username: root
  password:
  encoding: utf8
  host: localhost

development:
  database: reference_development
  <<: *login

production:
  database: reference_production
  <<: *login

test:
  database: reference_test
  <<: *login
